name: 🧪 Run Tests

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    name: 🔬 Unit Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: 📥 Checkout code
      uses: actions/checkout@v4

    - name: 🐹 Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        cache-dependency-path: api/go.sum

    - name: 📦 Cache Go modules
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('api/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: 🔧 Install dependencies
      working-directory: ./api
      run: go mod tidy

    - name: 🏗️ Build application
      working-directory: ./api
      run: go build -v .

    - name: 🧪 Run tests
      working-directory: ./api
      run: |
        go test -v -race -coverprofile=coverage.out ./...
        go tool cover -func=coverage.out

    - name: 📊 Generate coverage report
      working-directory: ./api
      run: go tool cover -html=coverage.out -o coverage.html

    - name: 📈 Upload coverage reports
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: |
          api/coverage.out
          api/coverage.html
        retention-days: 30

    - name: 🔍 Lint code
      uses: golangci/golangci-lint-action@v4
      with:
        version: latest
        working-directory: api
        args: --timeout=5m

  integration-test:
    name: 🔗 Integration Tests
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: 📥 Checkout code
      uses: actions/checkout@v4

    - name: 🐹 Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: 🐳 Build Docker image
      run: |
        docker build -t promptforge:test .

    - name: 🚀 Run container
      run: |
        docker run -d --name promptforge-test -p 8080:8080 promptforge:test
        sleep 10

    - name: 🔍 Health check
      run: |
        curl -f http://localhost:8080/api/health || exit 1
        echo "✅ Health check passed"

    - name: 🧹 Cleanup
      if: always()
      run: |
        docker stop promptforge-test || true
        docker rm promptforge-test || true

  security-scan:
    name: 🔒 Security Scan
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    permissions:
      contents: read
      security-events: write
    
    steps:
    - name: 📥 Checkout code
      uses: actions/checkout@v4

    - name: 🐹 Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: 🛡️ Run Gosec Security Scanner
      uses: securego/gosec@v2.22.5
      with:
        args: -fmt sarif -out gosec.sarif ./api/...

    - name: 🔎 Check if SARIF file exists
      run: |
        if [ -f gosec.sarif ]; then
          echo "✅ SARIF file generated successfully"
          echo "File size: $(ls -lh gosec.sarif | awk '{print $5}')"
          # Check if file has content
          if [ -s gosec.sarif ]; then
            echo "✅ SARIF file has content"
          else
            echo "⚠️ SARIF file is empty, creating minimal SARIF structure"
            cat > gosec.sarif << 'EOF'
        {
          "version": "2.1.0",
          "$schema": "https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Schemata/sarif-schema-2.1.0.json",
          "runs": []
        }
        EOF
          fi
        else
          echo "❌ SARIF file not found"
          ls -la
          echo "Creating empty SARIF file"
          cat > gosec.sarif << 'EOF'
        {
          "version": "2.1.0",
          "$schema": "https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Schemata/sarif-schema-2.1.0.json",
          "runs": []
        }
        EOF
        fi

    - name: 📤 Upload SARIF file
      uses: github/codeql-action/upload-sarif@v3
      if: always() && hashFiles('gosec.sarif') != ''
      with:
        sarif_file: gosec.sarif
        wait-for-processing: false 